"""change_destination_to_geography

Revision ID: 0a5eb59162a8
Revises: 73123b01e947
Create Date: 2026-05-20 03:58:53.133430

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2.types


# revision identifiers, used by Alembic.
revision: str = "0a5eb59162a8"
down_revision: Union[str, Sequence[str], None] = "73123b01e947"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "delivery_partners",
        sa.Column("max_handling_capacity", sa.Integer(), nullable=True),
    )
    op.drop_column("shipments", "destination")
    op.add_column(
        "shipments",
        sa.Column(
            "destination",
            geoalchemy2.types.Geography(geometry_type="POINT", srid=4326, name="geography"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shipments", "destination")
    op.add_column(
        "shipments",
        sa.Column("destination", sa.INTEGER(), nullable=True),
    )
    op.drop_column("delivery_partners", "max_handling_capacity")
    # ### end Alembic commands ###
