"""add_delivery_partner_shipment_relation

Revision ID: 337aa9762c20
Revises: 0a5eb59162a8
Create Date: 2026-05-20 04:11:27.736747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337aa9762c20'
down_revision: Union[str, Sequence[str], None] = '0a5eb59162a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('delivery_partner_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_shipments_delivery_partner_id', 'shipments', 'delivery_partners', ['delivery_partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_shipments_delivery_partner_id', 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'delivery_partner_id')
    # ### end Alembic commands ###
