"""add_created_at

Revision ID: 9ac460933cb0
Revises: 337aa9762c20
Create Date: 2026-05-20 04:19:17.617529

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ac460933cb0"
down_revision: Union[str, Sequence[str], None] = "337aa9762c20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "delivery_partners",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "sellers", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column(
        "shipments", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shipments", "created_at")
    op.drop_column("sellers", "created_at")
    op.drop_column("delivery_partners", "created_at")
    # ### end Alembic commands ###
