"""add_delivery_partner_locations_table

Revision ID: ea0029a07856
Revises: 9ac460933cb0
Create Date: 2026-05-20 04:49:38.512319

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "ea0029a07856"
down_revision: Union[str, Sequence[str], None] = "9ac460933cb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_partner_locations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("delivery_partner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["delivery_partner_id"],
            ["delivery_partners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_delivery_partner_locations_location",
        "delivery_partner_locations",
        ["location"],
        unique=False,
        postgresql_using="gist",
        if_not_exists=True,
    )
    op.drop_index(
        op.f("idx_delivery_partners_location"),
        table_name="delivery_partners",
        postgresql_using="gist",
    )
    op.drop_column("delivery_partners", "location")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "delivery_partners",
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("idx_delivery_partners_location"),
        "delivery_partners",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    op.drop_index(
        "idx_delivery_partner_locations_location",
        table_name="delivery_partner_locations",
        postgresql_using="gist",
    )
    op.drop_table("delivery_partner_locations")
    # ### end Alembic commands ###
